### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "User",
  "email": "user@gmail.com",
  "password": "pw1"
}

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "pw1"
} 


### Access Protected Route (add the token from login)
GET http://localhost:5000/api/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmVkYzllZGI4ZDMxMmVjNzFmM2JkZCIsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3NTczMzg3OTN9.J7i7y3kRqwx1evXNeUppQsDjc_7O3HQoaTFsc3Mz9NM