### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "",
  "email": "userone@gmail.com",
  "password": "pw1"
}

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "random@gmail.com",
  "password": "pw1"
} 


### Access Protected Route (add the token from login)
GET http://localhost:5000/api/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDYyNDdkYjRmNDBiOWEwNTY2ZjZmYSIsImVtYWlsIjoicmFuZG9tQGdtYWlsLmNvbSIsImlhdCI6MTc2MjA5NDE2Nn0.APNmmh66yxIXxkVmghlDTnA2szyrMmcBsV-w270dwcE