### ADD Movie to a watchlist
POST http://localhost:5000/api/watchlists/68beddb2db8d312ec71f3bf7/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmVkYzllZGI4ZDMxMmVjNzFmM2JkZCIsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3NTczMzkyNDN9.FB4ewkThjfNdKYragRGwhO1YW9er6roLAPsdBTFU52U
Content-Type: application/json

{
  "movieId": "68bdda5f86046341c116434c"
}

### Remove movie from Watchlist
DELETE http://localhost:5000/api/watchlists/68bdda5f86046341c116434c/movies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmVkYzllZGI4ZDMxMmVjNzFmM2JkZCIsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3NTczMzkyNDN9.FB4ewkThjfNdKYragRGwhO1YW9er6roLAPsdBTFU52U